//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woohoo.ChecksumDatabase.UnitTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Databases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Databases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Woohoo.ChecksumDatabase.UnitTest.Databases", typeof(Databases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clrmamepro (
        ///	name &quot;Atari ST - Compilations - Games - [ST]&quot;
        ///	description &quot;Atari ST - Compilations - Games - [ST] (TOSEC-v2006-10-22)&quot;
        ///	category &quot;Atari ST - Compilations - Games - [ST]&quot;
        ///	version 2006-10-22
        ///	author Keili - jjs - Laokoon - Grendel - dirkpitt - Jacek - Steph
        ///)
        ///
        ///game (
        ///	name &quot;Abominaball (1992)(ST Format) &amp; Kid Kong (19xx)(Atari ST Magazine)&quot;
        ///	description &quot;Abominaball (1992)(ST Format) &amp; Kid Kong (19xx)(Atari ST Magazine)&quot;
        ///	rom ( name &quot;Abominaball (1992)(ST Format) &amp; Kid Kong (19xx)(A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Atari_ST___Compilations___Games____ST___TOSEC_v2006_10_22_CM_ {
            get {
                return ResourceManager.GetString("Atari_ST___Compilations___Games____ST___TOSEC_v2006_10_22_CM_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!DOCTYPE datafile PUBLIC &quot;-//Logiqx//DTD ROM Management Datafile//EN&quot; &quot;http://www.logiqx.com/Dats/datafile.dtd&quot;&gt;
        ///
        ///&lt;datafile&gt;
        ///	&lt;header&gt;
        ///		&lt;name&gt;Hartung - Game Master&lt;/name&gt;
        ///		&lt;description&gt;Hartung - Game Master&lt;/description&gt;
        ///		&lt;category&gt;no-intro romset&lt;/category&gt;
        ///		&lt;version&gt;20080716&lt;/version&gt;
        ///		&lt;author&gt;incog | www.no-intro.org&lt;/author&gt;
        ///		&lt;clrmamepro/&gt;
        ///	&lt;/header&gt;
        ///	&lt;game name=&quot;[Bios] Hartung Game Master&quot;&gt;
        ///		&lt;description&gt;[Bios] Hartung Game Master&lt;/description&gt;
        ///		&lt;manufacture [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Hartung___Game_Master__20080716_ {
            get {
                return ResourceManager.GetString("Hartung___Game_Master__20080716_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clrmamepro (
        ///	name &quot;Nintendo - Virtual Boy&quot;
        ///	description &quot;Nintendo - Virtual Boy&quot;
        ///	category &quot;no-intro romset&quot;
        ///	version 20071103
        ///	author &quot;BigFred | www.gbadat.altervista.org&quot;
        ///)
        ///
        ///game (
        ///	name &quot;3-D Tetris (USA)&quot;
        ///	description &quot;3-D Tetris (USA)&quot;
        ///	rom ( name &quot;3-D Tetris (USA).vb&quot; size 1048576 crc bb71b522 md5 ecf1218706e9b547eab9e4be58d54e21 sha1 5177015a91442e56bd76af39447bca365e06c272 )
        ///)
        ///
        ///game (
        ///	name &quot;Galactic Pinball (Japan, USA)&quot;
        ///	description &quot;Galactic Pinball (Japan, USA)&quot;
        ///	rom ( name &quot;Gal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nintendo___Virtual_Boy__20071103_ {
            get {
                return ResourceManager.GetString("Nintendo___Virtual_Boy__20071103_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clrmamepro (
        ///	name &quot;Sega Dreamcast - Games - [GDI]&quot;
        ///	description &quot;Sega Dreamcast - Games - [GDI] (TOSEC-v2007-12-30)&quot;
        ///	category &quot;Sega Dreamcast - Games - [GDI]&quot;
        ///	version 2007-12-30
        ///	author Maddog
        ///)
        ///
        ///game (
        ///	name &quot;102 Dalmatians - Puppies to the Rescue v1.001 (2000)(EIDOS)(NTSC)(US)[!]&quot;
        ///	description &quot;102 Dalmatians - Puppies to the Rescue v1.001 (2000)(EIDOS)(NTSC)(US)[!]&quot;
        ///	rom ( name &quot;102 Dalmatians - Puppies to the Rescue v1.001 (2000)(EIDOS)(NTSC)(US)[!].gdi&quot; size 149 crc f196cf72 md5 b57138b38 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sega_Dreamcast___Games____GDI___TOSEC_v2007_12_30_CM_ {
            get {
                return ResourceManager.GetString("Sega_Dreamcast___Games____GDI___TOSEC_v2007_12_30_CM_", resourceCulture);
            }
        }
    }
}
