//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woohoo.ChecksumDatabase.Serialization.Extensions.Mame.Model;

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class mame
{

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("machine")]
    public machine[] machine;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string build;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(mameDebug.no)]
    public mameDebug debug;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mameconfig;

    public mame()
    {
        this.debug = mameDebug.no;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class machine
{

    /// <remarks/>
    public string description;

    /// <remarks/>
    public string year;

    /// <remarks/>
    public string manufacturer;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("biosset")]
    public biosset[] biosset;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("rom")]
    public rom[] rom;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("disk")]
    public disk[] disk;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("device_ref")]
    public device_ref[] device_ref;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sample")]
    public sample[] sample;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("chip")]
    public chip[] chip;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("display")]
    public display[] display;

    /// <remarks/>
    public sound sound;

    /// <remarks/>
    public input input;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("dipswitch")]
    public dipswitch[] dipswitch;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("configuration")]
    public configuration[] configuration;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("port")]
    public port[] port;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("adjuster")]
    public adjuster[] adjuster;

    /// <remarks/>
    public driver driver;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("feature")]
    public feature[] feature;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("device")]
    public device[] device;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("slot")]
    public slot[] slot;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("softwarelist")]
    public softwarelist[] softwarelist;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ramoption")]
    public ramoption[] ramoption;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sourcefile;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(machineIsbios.no)]
    public machineIsbios isbios;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(machineIsdevice.no)]
    public machineIsdevice isdevice;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(machineIsmechanical.no)]
    public machineIsmechanical ismechanical;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(machineRunnable.yes)]
    public machineRunnable runnable;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cloneof;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string romof;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sampleof;

    public machine()
    {
        this.isbios = machineIsbios.no;
        this.isdevice = machineIsdevice.no;
        this.ismechanical = machineIsmechanical.no;
        this.runnable = machineRunnable.yes;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class biosset
{

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string description;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(biossetDefault.no)]
    public biossetDefault @default;

    public biosset()
    {
        this.@default = biossetDefault.no;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public enum biossetDefault
{

    /// <remarks/>
    yes,

    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class rom
{

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string bios;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string size;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string crc;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sha1;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string merge;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string region;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string offset;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(romStatus.good)]
    public romStatus status;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(romOptional.no)]
    public romOptional optional;

    public rom()
    {
        this.status = romStatus.good;
        this.optional = romOptional.no;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public enum romStatus
{

    /// <remarks/>
    baddump,

    /// <remarks/>
    nodump,

    /// <remarks/>
    good,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public enum romOptional
{

    /// <remarks/>
    yes,

    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class disk
{

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sha1;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string merge;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string region;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string index;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(diskWritable.no)]
    public diskWritable writable;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(diskStatus.good)]
    public diskStatus status;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(diskOptional.no)]
    public diskOptional optional;

    public disk()
    {
        this.writable = diskWritable.no;
        this.status = diskStatus.good;
        this.optional = diskOptional.no;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public enum diskWritable
{

    /// <remarks/>
    yes,

    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public enum diskStatus
{

    /// <remarks/>
    baddump,

    /// <remarks/>
    nodump,

    /// <remarks/>
    good,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public enum diskOptional
{

    /// <remarks/>
    yes,

    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class device_ref
{

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class sample
{

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class chip
{

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tag;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public chipType type;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clock;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public enum chipType
{

    /// <remarks/>
    cpu,

    /// <remarks/>
    audio,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class display
{

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tag;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public displayType type;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public displayRotate rotate;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool rotateSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(displayFlipx.no)]
    public displayFlipx flipx;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string width;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string height;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string refresh;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pixclock;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string htotal;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hbend;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hbstart;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string vtotal;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string vbend;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string vbstart;

    public display()
    {
        this.flipx = displayFlipx.no;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public enum displayType
{

    /// <remarks/>
    raster,

    /// <remarks/>
    vector,

    /// <remarks/>
    lcd,

    /// <remarks/>
    svg,

    /// <remarks/>
    unknown,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public enum displayRotate
{

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("90")]
    Item90,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("180")]
    Item180,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("270")]
    Item270,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public enum displayFlipx
{

    /// <remarks/>
    yes,

    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class sound
{

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string channels;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class input
{

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("control")]
    public control[] control;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(inputService.no)]
    public inputService service;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(inputTilt.no)]
    public inputTilt tilt;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string players;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string coins;

    public input()
    {
        this.service = inputService.no;
        this.tilt = inputTilt.no;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class control
{

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string player;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string buttons;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string reqbuttons;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string minimum;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string maximum;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sensitivity;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string keydelta;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(controlReverse.no)]
    public controlReverse reverse;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ways;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ways2;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ways3;

    public control()
    {
        this.reverse = controlReverse.no;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public enum controlReverse
{

    /// <remarks/>
    yes,

    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public enum inputService
{

    /// <remarks/>
    yes,

    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public enum inputTilt
{

    /// <remarks/>
    yes,

    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class dipswitch
{

    /// <remarks/>
    public condition condition;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("diplocation")]
    public diplocation[] diplocation;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("dipvalue")]
    public dipvalue[] dipvalue;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tag;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mask;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class condition
{

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tag;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mask;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public conditionRelation relation;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public enum conditionRelation
{

    /// <remarks/>
    eq,

    /// <remarks/>
    ne,

    /// <remarks/>
    gt,

    /// <remarks/>
    le,

    /// <remarks/>
    lt,

    /// <remarks/>
    ge,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class diplocation
{

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string number;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(diplocationInverted.no)]
    public diplocationInverted inverted;

    public diplocation()
    {
        this.inverted = diplocationInverted.no;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public enum diplocationInverted
{

    /// <remarks/>
    yes,

    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class dipvalue
{

    /// <remarks/>
    public condition condition;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(dipvalueDefault.no)]
    public dipvalueDefault @default;

    public dipvalue()
    {
        this.@default = dipvalueDefault.no;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public enum dipvalueDefault
{

    /// <remarks/>
    yes,

    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class configuration
{

    /// <remarks/>
    public condition condition;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("conflocation")]
    public conflocation[] conflocation;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("confsetting")]
    public confsetting[] confsetting;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tag;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mask;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class conflocation
{

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string number;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(conflocationInverted.no)]
    public conflocationInverted inverted;

    public conflocation()
    {
        this.inverted = conflocationInverted.no;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public enum conflocationInverted
{

    /// <remarks/>
    yes,

    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class confsetting
{

    /// <remarks/>
    public condition condition;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(confsettingDefault.no)]
    public confsettingDefault @default;

    public confsetting()
    {
        this.@default = confsettingDefault.no;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public enum confsettingDefault
{

    /// <remarks/>
    yes,

    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class port
{

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("analog")]
    public analog[] analog;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tag;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class analog
{

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mask;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class adjuster
{

    /// <remarks/>
    public condition condition;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @default;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class driver
{

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public driverStatus status;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public driverEmulation emulation;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public driverCocktail cocktail;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool cocktailSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public driverSavestate savestate;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(driverRequiresartwork.no)]
    public driverRequiresartwork requiresartwork;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(driverUnofficial.no)]
    public driverUnofficial unofficial;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(driverNosoundhardware.no)]
    public driverNosoundhardware nosoundhardware;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(driverIncomplete.no)]
    public driverIncomplete incomplete;

    public driver()
    {
        this.requiresartwork = driverRequiresartwork.no;
        this.unofficial = driverUnofficial.no;
        this.nosoundhardware = driverNosoundhardware.no;
        this.incomplete = driverIncomplete.no;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public enum driverStatus
{

    /// <remarks/>
    good,

    /// <remarks/>
    imperfect,

    /// <remarks/>
    preliminary,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public enum driverEmulation
{

    /// <remarks/>
    good,

    /// <remarks/>
    imperfect,

    /// <remarks/>
    preliminary,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public enum driverCocktail
{

    /// <remarks/>
    good,

    /// <remarks/>
    imperfect,

    /// <remarks/>
    preliminary,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public enum driverSavestate
{

    /// <remarks/>
    supported,

    /// <remarks/>
    unsupported,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public enum driverRequiresartwork
{

    /// <remarks/>
    yes,

    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public enum driverUnofficial
{

    /// <remarks/>
    yes,

    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public enum driverNosoundhardware
{

    /// <remarks/>
    yes,

    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public enum driverIncomplete
{

    /// <remarks/>
    yes,

    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class feature
{

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public featureType type;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public featureStatus status;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool statusSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public featureOverall overall;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool overallSpecified;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public enum featureType
{

    /// <remarks/>
    protection,

    /// <remarks/>
    timing,

    /// <remarks/>
    graphics,

    /// <remarks/>
    palette,

    /// <remarks/>
    sound,

    /// <remarks/>
    capture,

    /// <remarks/>
    camera,

    /// <remarks/>
    microphone,

    /// <remarks/>
    controls,

    /// <remarks/>
    keyboard,

    /// <remarks/>
    mouse,

    /// <remarks/>
    media,

    /// <remarks/>
    disk,

    /// <remarks/>
    printer,

    /// <remarks/>
    tape,

    /// <remarks/>
    punch,

    /// <remarks/>
    drum,

    /// <remarks/>
    rom,

    /// <remarks/>
    comms,

    /// <remarks/>
    lan,

    /// <remarks/>
    wan,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public enum featureStatus
{

    /// <remarks/>
    unemulated,

    /// <remarks/>
    imperfect,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public enum featureOverall
{

    /// <remarks/>
    unemulated,

    /// <remarks/>
    imperfect,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class device
{

    /// <remarks/>
    public instance instance;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("extension")]
    public @extension[] extension;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tag;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fixed_image;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mandatory;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @interface;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class instance
{

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string briefname;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class @extension
{

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class slot
{

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("slotoption")]
    public slotoption[] slotoption;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class slotoption
{

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string devname;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(slotoptionDefault.no)]
    public slotoptionDefault @default;

    public slotoption()
    {
        this.@default = slotoptionDefault.no;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public enum slotoptionDefault
{

    /// <remarks/>
    yes,

    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class softwarelist
{

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tag;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public softwarelistStatus status;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string filter;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public enum softwarelistStatus
{

    /// <remarks/>
    original,

    /// <remarks/>
    compatible,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class ramoption
{

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @default;

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public enum machineIsbios
{

    /// <remarks/>
    yes,

    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public enum machineIsdevice
{

    /// <remarks/>
    yes,

    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public enum machineIsmechanical
{

    /// <remarks/>
    yes,

    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public enum machineRunnable
{

    /// <remarks/>
    yes,

    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public enum mameDebug
{

    /// <remarks/>
    yes,

    /// <remarks/>
    no,
}
