//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woohoo.ChecksumMatcher.WinUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localized {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localized() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Woohoo.ChecksumMatcher.WinUI.Localized", typeof(Localized).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Explorer.
        /// </summary>
        public static string AppNotificationOpenInExplorer {
            get {
                return ResourceManager.GetString("AppNotificationOpenInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string AuditPageBrowse {
            get {
                return ResourceManager.GetString("AuditPageBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a database to audit files.
        /// </summary>
        public static string AuditPageNoDatabaseSelectedSubtitle {
            get {
                return ResourceManager.GetString("AuditPageNoDatabaseSelectedSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No database selected.
        /// </summary>
        public static string AuditPageNoDatabaseSelectedTitle {
            get {
                return ResourceManager.GetString("AuditPageNoDatabaseSelectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source folder.
        /// </summary>
        public static string AuditPageSourceFolder {
            get {
                return ResourceManager.GetString("AuditPageSourceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string AuditPageStart {
            get {
                return ResourceManager.GetString("AuditPageStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ConfirmationDialogCancel {
            get {
                return ResourceManager.GetString("ConfirmationDialogCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ConfirmationDialogOK {
            get {
                return ResourceManager.GetString("ConfirmationDialogOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string ContainerTypeFolder {
            get {
                return ResourceManager.GetString("ContainerTypeFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7z (Uncompressed).
        /// </summary>
        public static string ContainerTypeSevenZipUncompressed {
            get {
                return ResourceManager.GetString("ContainerTypeSevenZipUncompressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torrent7z.
        /// </summary>
        public static string ContainerTypeTorrentSevenZip {
            get {
                return ResourceManager.GetString("ContainerTypeTorrentSevenZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TorrentZip.
        /// </summary>
        public static string ContainerTypeTorrentZip {
            get {
                return ResourceManager.GetString("ContainerTypeTorrentZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        public static string ContainerTypeZip {
            get {
                return ResourceManager.GetString("ContainerTypeZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create database was cancelled.
        /// </summary>
        public static string CreateDatabaseCancelNotification {
            get {
                return ResourceManager.GetString("CreateDatabaseCancelNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create database failed.
        /// </summary>
        public static string CreateDatabaseErrorNotification {
            get {
                return ResourceManager.GetString("CreateDatabaseErrorNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Current UTC (yyyyMMdd-HHmmss).
        /// </summary>
        public static string CreateDatabaseInsertDateTimeNoIntro {
            get {
                return ResourceManager.GetString("CreateDatabaseInsertDateTimeNoIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Current UTC (yyyy-MM-dd HH-mm-ss).
        /// </summary>
        public static string CreateDatabaseInsertDateTimeRedump {
            get {
                return ResourceManager.GetString("CreateDatabaseInsertDateTimeRedump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string CreateDatabasePageAuthor {
            get {
                return ResourceManager.GetString("CreateDatabasePageAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string CreateDatabasePageBrowse {
            get {
                return ResourceManager.GetString("CreateDatabasePageBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CreateDatabasePageName {
            get {
                return ResourceManager.GetString("CreateDatabasePageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source folder.
        /// </summary>
        public static string CreateDatabasePageSourceFolder {
            get {
                return ResourceManager.GetString("CreateDatabasePageSourceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string CreateDatabasePageStart {
            get {
                return ResourceManager.GetString("CreateDatabasePageStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database destination file.
        /// </summary>
        public static string CreateDatabasePageTargetDatabaseFile {
            get {
                return ResourceManager.GetString("CreateDatabasePageTargetDatabaseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string CreateDatabasePageVersion {
            get {
                return ResourceManager.GetString("CreateDatabasePageVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Files (*.dat).
        /// </summary>
        public static string CreateDatabaseSaveFilter {
            get {
                return ResourceManager.GetString("CreateDatabaseSaveFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists and will be replaced.
        /// </summary>
        public static string CreateDatabaseStatusFileExists {
            get {
                return ResourceManager.GetString("CreateDatabaseStatusFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create database completed.
        /// </summary>
        public static string CreateDatabaseSuccessNotification {
            get {
                return ResourceManager.GetString("CreateDatabaseSuccessNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled..
        /// </summary>
        public static string DatabaseCreateProgressCanceled {
            get {
                return ResourceManager.GetString("DatabaseCreateProgressCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed at {0}..
        /// </summary>
        public static string DatabaseCreateProgressCompleteFormat {
            get {
                return ResourceManager.GetString("DatabaseCreateProgressCompleteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation error: {0}.
        /// </summary>
        public static string DatabaseCreateProgressErrorFormat {
            get {
                return ResourceManager.GetString("DatabaseCreateProgressErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hashing &apos;{0}&apos;..
        /// </summary>
        public static string DatabaseCreateProgressHashingFormat {
            get {
                return ResourceManager.GetString("DatabaseCreateProgressHashingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending..
        /// </summary>
        public static string DatabaseCreateProgressPending {
            get {
                return ResourceManager.GetString("DatabaseCreateProgressPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning..
        /// </summary>
        public static string DatabaseCreateProgressScanning {
            get {
                return ResourceManager.GetString("DatabaseCreateProgressScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started..
        /// </summary>
        public static string DatabaseCreateProgressStarted {
            get {
                return ResourceManager.GetString("DatabaseCreateProgressStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a database to view its information.
        /// </summary>
        public static string DatabaseInfoPageNoDatabaseSelectedSubtitle {
            get {
                return ResourceManager.GetString("DatabaseInfoPageNoDatabaseSelectedSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No database selected.
        /// </summary>
        public static string DatabaseInfoPageNoDatabaseSelectedTitle {
            get {
                return ResourceManager.GetString("DatabaseInfoPageNoDatabaseSelectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRC32:.
        /// </summary>
        public static string DatabasePageCrc32 {
            get {
                return ResourceManager.GetString("DatabasePageCrc32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File:.
        /// </summary>
        public static string DatabasePageFile {
            get {
                return ResourceManager.GetString("DatabasePageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD5:.
        /// </summary>
        public static string DatabasePageMd5 {
            get {
                return ResourceManager.GetString("DatabasePageMd5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy CRC32.
        /// </summary>
        public static string DatabasePageMenuItemCopyCrc32 {
            get {
                return ResourceManager.GetString("DatabasePageMenuItemCopyCrc32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy MD5.
        /// </summary>
        public static string DatabasePageMenuItemCopyMd5 {
            get {
                return ResourceManager.GetString("DatabasePageMenuItemCopyMd5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Name.
        /// </summary>
        public static string DatabasePageMenuItemCopyName {
            get {
                return ResourceManager.GetString("DatabasePageMenuItemCopyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy SHA1.
        /// </summary>
        public static string DatabasePageMenuItemCopySha1 {
            get {
                return ResourceManager.GetString("DatabasePageMenuItemCopySha1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Size.
        /// </summary>
        public static string DatabasePageMenuItemCopySize {
            get {
                return ResourceManager.GetString("DatabasePageMenuItemCopySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a database to view its contents.
        /// </summary>
        public static string DatabasePageNoDatabaseSelectedSubtitle {
            get {
                return ResourceManager.GetString("DatabasePageNoDatabaseSelectedSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No database selected.
        /// </summary>
        public static string DatabasePageNoDatabaseSelectedTitle {
            get {
                return ResourceManager.GetString("DatabasePageNoDatabaseSelectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Database.
        /// </summary>
        public static string DatabasePageSearchWatermark {
            get {
                return ResourceManager.GetString("DatabasePageSearchWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA1:.
        /// </summary>
        public static string DatabasePageSha1 {
            get {
                return ResourceManager.GetString("DatabasePageSha1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        public static string DatabasePageSize {
            get {
                return ResourceManager.GetString("DatabasePageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string DatabasesPageAuthor {
            get {
                return ResourceManager.GetString("DatabasesPageAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count:.
        /// </summary>
        public static string DatabasesPageCount {
            get {
                return ResourceManager.GetString("DatabasesPageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Databases.
        /// </summary>
        public static string DatabasesPageSearchWatermark {
            get {
                return ResourceManager.GetString("DatabasesPageSearchWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        public static string DatabasesPageSize {
            get {
                return ResourceManager.GetString("DatabasesPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string DatabasesPageVersion {
            get {
                return ResourceManager.GetString("DatabasesPageVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download was cancelled.
        /// </summary>
        public static string DownloadCancelNotification {
            get {
                return ResourceManager.GetString("DownloadCancelNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed.
        /// </summary>
        public static string DownloadErrorNotification {
            get {
                return ResourceManager.GetString("DownloadErrorNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download completed.
        /// </summary>
        public static string DownloadSuccessNotification {
            get {
                return ResourceManager.GetString("DownloadSuccessNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string DumpStatusFilterDescriptionAll {
            get {
                return ResourceManager.GetString("DumpStatusFilterDescriptionAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad.
        /// </summary>
        public static string DumpStatusFilterDescriptionBad {
            get {
                return ResourceManager.GetString("DumpStatusFilterDescriptionBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string DumpStatusFilterDescriptionGood {
            get {
                return ResourceManager.GetString("DumpStatusFilterDescriptionGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoDump.
        /// </summary>
        public static string DumpStatusFilterDescriptionNoDump {
            get {
                return ResourceManager.GetString("DumpStatusFilterDescriptionNoDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        public static string DumpStatusFilterDescriptionVerified {
            get {
                return ResourceManager.GetString("DumpStatusFilterDescriptionVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        public static string FileFilterAll {
            get {
                return ResourceManager.GetString("FileFilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Files.
        /// </summary>
        public static string FileFilterDatabase {
            get {
                return ResourceManager.GetString("FileFilterDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Md5 Files.
        /// </summary>
        public static string FileFilterMd5 {
            get {
                return ResourceManager.GetString("FileFilterMd5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sfv Files.
        /// </summary>
        public static string FileFilterSfv {
            get {
                return ResourceManager.GetString("FileFilterSfv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} bytes.
        /// </summary>
        public static string FileSizeInB {
            get {
                return ResourceManager.GetString("FileSizeInB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} GB.
        /// </summary>
        public static string FileSizeInGB {
            get {
                return ResourceManager.GetString("FileSizeInGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} KB.
        /// </summary>
        public static string FileSizeInKB {
            get {
                return ResourceManager.GetString("FileSizeInKB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} MB.
        /// </summary>
        public static string FileSizeInMB {
            get {
                return ResourceManager.GetString("FileSizeInMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} TB.
        /// </summary>
        public static string FileSizeInTB {
            get {
                return ResourceManager.GetString("FileSizeInTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder does not exist.
        /// </summary>
        public static string FolderDetailsDoesNotExist {
            get {
                return ResourceManager.GetString("FolderDetailsDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} folder(s), {1} file(s).
        /// </summary>
        public static string FolderDetailsFormat {
            get {
                return ResourceManager.GetString("FolderDetailsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} folders, {1} files.
        /// </summary>
        public static string FolderDetailsMultipleFoldersMultipleFilesFormat {
            get {
                return ResourceManager.GetString("FolderDetailsMultipleFoldersMultipleFilesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} folders, {1} file.
        /// </summary>
        public static string FolderDetailsMultipleFoldersOneFileFormat {
            get {
                return ResourceManager.GetString("FolderDetailsMultipleFoldersOneFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} folder, {1} files.
        /// </summary>
        public static string FolderDetailsOneFolderMultipleFilesFormat {
            get {
                return ResourceManager.GetString("FolderDetailsOneFolderMultipleFilesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} folder, {1} file.
        /// </summary>
        public static string FolderDetailsOneFolderOneFileFormat {
            get {
                return ResourceManager.GetString("FolderDetailsOneFolderOneFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string HashCalculatorPageBrowse {
            get {
                return ResourceManager.GetString("HashCalculatorPageBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string HashCalculatorPageCopy {
            get {
                return ResourceManager.GetString("HashCalculatorPageCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRC32.
        /// </summary>
        public static string HashCalculatorPageFileCrc32 {
            get {
                return ResourceManager.GetString("HashCalculatorPageFileCrc32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD5.
        /// </summary>
        public static string HashCalculatorPageFileMd5 {
            get {
                return ResourceManager.GetString("HashCalculatorPageFileMd5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string HashCalculatorPageFileName {
            get {
                return ResourceManager.GetString("HashCalculatorPageFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA1.
        /// </summary>
        public static string HashCalculatorPageFileSha1 {
            get {
                return ResourceManager.GetString("HashCalculatorPageFileSha1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA256.
        /// </summary>
        public static string HashCalculatorPageFileSha256 {
            get {
                return ResourceManager.GetString("HashCalculatorPageFileSha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string HashCalculatorPageFileSize {
            get {
                return ResourceManager.GetString("HashCalculatorPageFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRC32: {0}.
        /// </summary>
        public static string HashCalculatorPageResultCrc32 {
            get {
                return ResourceManager.GetString("HashCalculatorPageResultCrc32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File: {0}.
        /// </summary>
        public static string HashCalculatorPageResultFileName {
            get {
                return ResourceManager.GetString("HashCalculatorPageResultFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size: {0}.
        /// </summary>
        public static string HashCalculatorPageResultFileSize {
            get {
                return ResourceManager.GetString("HashCalculatorPageResultFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD5: {0}.
        /// </summary>
        public static string HashCalculatorPageResultMd5 {
            get {
                return ResourceManager.GetString("HashCalculatorPageResultMd5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA1: {0}.
        /// </summary>
        public static string HashCalculatorPageResultSha1 {
            get {
                return ResourceManager.GetString("HashCalculatorPageResultSha1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA256: {0}.
        /// </summary>
        public static string HashCalculatorPageResultSha256 {
            get {
                return ResourceManager.GetString("HashCalculatorPageResultSha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Browse or drag and drop a file to calculate its checksums.
        /// </summary>
        public static string HashCalculatorPageSubtitle {
            get {
                return ResourceManager.GetString("HashCalculatorPageSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate file hash.
        /// </summary>
        public static string HashCalculatorPageTitle {
            get {
                return ResourceManager.GetString("HashCalculatorPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string HeaderAuthor {
            get {
                return ResourceManager.GetString("HeaderAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string HeaderCategory {
            get {
                return ResourceManager.GetString("HeaderCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string HeaderComment {
            get {
                return ResourceManager.GetString("HeaderComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string HeaderDate {
            get {
                return ResourceManager.GetString("HeaderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string HeaderDescription {
            get {
                return ResourceManager.GetString("HeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string HeaderEmail {
            get {
                return ResourceManager.GetString("HeaderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        public static string HeaderHomepage {
            get {
                return ResourceManager.GetString("HeaderHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string HeaderName {
            get {
                return ResourceManager.GetString("HeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string HeaderUrl {
            get {
                return ResourceManager.GetString("HeaderUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string HeaderVersion {
            get {
                return ResourceManager.GetString("HeaderVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan your files to see if they match the files in the database..
        /// </summary>
        public static string HomePageAuditSubtitle {
            get {
                return ResourceManager.GetString("HomePageAuditSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit your files.
        /// </summary>
        public static string HomePageAuditTitle {
            get {
                return ResourceManager.GetString("HomePageAuditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the location of the database files..
        /// </summary>
        public static string HomePageConfigureLibrarySubtitle {
            get {
                return ResourceManager.GetString("HomePageConfigureLibrarySubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure your database folders.
        /// </summary>
        public static string HomePageConfigureLibraryTitle {
            get {
                return ResourceManager.GetString("HomePageConfigureLibraryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a database by scanning files in a folder..
        /// </summary>
        public static string HomePageCreateDatabaseSubtitle {
            get {
                return ResourceManager.GetString("HomePageCreateDatabaseSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a checksum database.
        /// </summary>
        public static string HomePageCreateDatabaseTitle {
            get {
                return ResourceManager.GetString("HomePageCreateDatabaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No-Intro is mainly a cart preservation database. It lists only the best available ROM; ideally this will be a full dump with no faults and changes to the file, basically just the ROMS that are the closest as possible to the original licensed cartridges..
        /// </summary>
        public static string HomePageDownloadNoIntroDescription {
            get {
                return ResourceManager.GetString("HomePageDownloadNoIntroDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best available game cartridges..
        /// </summary>
        public static string HomePageDownloadNoIntroSubtitle {
            get {
                return ResourceManager.GetString("HomePageDownloadNoIntroSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No-Intro.
        /// </summary>
        public static string HomePageDownloadNoIntroTitle {
            get {
                return ResourceManager.GetString("HomePageDownloadNoIntroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://no-intro.org/.
        /// </summary>
        public static string HomePageDownloadNoIntroUrl {
            get {
                return ResourceManager.GetString("HomePageDownloadNoIntroUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redump.org is a disc preservation database and community dedicated to collecting precise and accurate information about every video game ever released on optical media of any system..
        /// </summary>
        public static string HomePageDownloadRedumpDescription {
            get {
                return ResourceManager.GetString("HomePageDownloadRedumpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video game optical media..
        /// </summary>
        public static string HomePageDownloadRedumpSubtitle {
            get {
                return ResourceManager.GetString("HomePageDownloadRedumpSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redump.
        /// </summary>
        public static string HomePageDownloadRedumpTitle {
            get {
                return ResourceManager.GetString("HomePageDownloadRedumpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.redump.org.
        /// </summary>
        public static string HomePageDownloadRedumpUrl {
            get {
                return ResourceManager.GetString("HomePageDownloadRedumpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Old School Emulation Center (TOSEC) is a retrocomputing initiative dedicated to the cataloging and preservation of software, firmware and resources for arcade machines, microcomputers, minicomputers and video game consoles. The main goal of the project is to catalog and audit various kinds of software and firmware images for these systems..
        /// </summary>
        public static string HomePageDownloadTosecDescription {
            get {
                return ResourceManager.GetString("HomePageDownloadTosecDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing sets of old media..
        /// </summary>
        public static string HomePageDownloadTosecSubtitle {
            get {
                return ResourceManager.GetString("HomePageDownloadTosecSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOSEC.
        /// </summary>
        public static string HomePageDownloadTosecTitle {
            get {
                return ResourceManager.GetString("HomePageDownloadTosecTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.tosecdev.org/.
        /// </summary>
        public static string HomePageDownloadTosecUrl {
            get {
                return ResourceManager.GetString("HomePageDownloadTosecUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit your files.
        /// </summary>
        public static string HomePageGroupAudit {
            get {
                return ResourceManager.GetString("HomePageGroupAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your own databases.
        /// </summary>
        public static string HomePageGroupCreateDatabase {
            get {
                return ResourceManager.GetString("HomePageGroupCreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download databases from online preservation groups.
        /// </summary>
        public static string HomePageGroupDownload {
            get {
                return ResourceManager.GetString("HomePageGroupDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash files.
        /// </summary>
        public static string HomePageGroupHashFile {
            get {
                return ResourceManager.GetString("HomePageGroupHashFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate and display an individual file&apos;s CRC32, MD5 and SHA1 checksums.
        /// </summary>
        public static string HomePageHashFileSubtitle {
            get {
                return ResourceManager.GetString("HomePageHashFileSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate file hash.
        /// </summary>
        public static string HomePageHashFileTitle {
            get {
                return ResourceManager.GetString("HomePageHashFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the database you would like to view / use to audit your files..
        /// </summary>
        public static string HomePageSelectDatabaseSubtitle {
            get {
                return ResourceManager.GetString("HomePageSelectDatabaseSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a database.
        /// </summary>
        public static string HomePageSelectDatabaseTitle {
            get {
                return ResourceManager.GetString("HomePageSelectDatabaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a .sfv or .md5 file to validate its contents.
        /// </summary>
        public static string HomePageValidateSubtitle {
            get {
                return ResourceManager.GetString("HomePageValidateSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate using a checksum file.
        /// </summary>
        public static string HomePageValidateTitle {
            get {
                return ResourceManager.GetString("HomePageValidateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checksum Matcher.
        /// </summary>
        public static string MainWindowCaption {
            get {
                return ResourceManager.GetString("MainWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit.
        /// </summary>
        public static string MainWindowNavigationAudit {
            get {
                return ResourceManager.GetString("MainWindowNavigationAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string MainWindowNavigationCreate {
            get {
                return ResourceManager.GetString("MainWindowNavigationCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash.
        /// </summary>
        public static string MainWindowNavigationHash {
            get {
                return ResourceManager.GetString("MainWindowNavigationHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MainWindowNavigationHome {
            get {
                return ResourceManager.GetString("MainWindowNavigationHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string MainWindowNavigationInfo {
            get {
                return ResourceManager.GetString("MainWindowNavigationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string MainWindowNavigationLibrary {
            get {
                return ResourceManager.GetString("MainWindowNavigationLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        public static string MainWindowNavigationQuery {
            get {
                return ResourceManager.GetString("MainWindowNavigationQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild.
        /// </summary>
        public static string MainWindowNavigationRebuild {
            get {
                return ResourceManager.GetString("MainWindowNavigationRebuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainWindowNavigationSettings {
            get {
                return ResourceManager.GetString("MainWindowNavigationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string MainWindowNavigationValidate {
            get {
                return ResourceManager.GetString("MainWindowNavigationValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create offline storage was cancelled.
        /// </summary>
        public static string OfflineDiskCancelNotification {
            get {
                return ResourceManager.GetString("OfflineDiskCancelNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create offline storage failed.
        /// </summary>
        public static string OfflineDiskErrorNotification {
            get {
                return ResourceManager.GetString("OfflineDiskErrorNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation of &apos;{0}&apos; canceled..
        /// </summary>
        public static string OfflineDiskProgressCanceledFormat {
            get {
                return ResourceManager.GetString("OfflineDiskProgressCanceledFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation of &apos;{0}&apos; complete at {1}..
        /// </summary>
        public static string OfflineDiskProgressCompleteFormat {
            get {
                return ResourceManager.GetString("OfflineDiskProgressCompleteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation of &apos;{0}&apos; complete ({1} folders, {2} files, {3} archive items)  {4:0.0} secs at {5}..
        /// </summary>
        public static string OfflineDiskProgressCompleteFormatWithStats {
            get {
                return ResourceManager.GetString("OfflineDiskProgressCompleteFormatWithStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating offline storage &apos;{0}&apos;.
        /// </summary>
        public static string OfflineDiskProgressCreatingFormat {
            get {
                return ResourceManager.GetString("OfflineDiskProgressCreatingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating offline storage &apos;{0}&apos; ({1} folders, {2} files, {3} archive items) in {4:0.0} secs..
        /// </summary>
        public static string OfflineDiskProgressCreatingFormatWithStats {
            get {
                return ResourceManager.GetString("OfflineDiskProgressCreatingFormatWithStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation error: {0}.
        /// </summary>
        public static string OfflineDiskProgressErrorFormat {
            get {
                return ResourceManager.GetString("OfflineDiskProgressErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists and will be replaced.
        /// </summary>
        public static string OfflineDiskProgressFileExists {
            get {
                return ResourceManager.GetString("OfflineDiskProgressFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists and will be replaced.
        /// </summary>
        public static string OfflineDiskProgressFileExists1 {
            get {
                return ResourceManager.GetString("OfflineDiskProgressFileExists1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create offline storage completed.
        /// </summary>
        public static string OfflineDiskSuccessNotification {
            get {
                return ResourceManager.GetString("OfflineDiskSuccessNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string OfflineStorageFolderSelectionDialogCancel {
            get {
                return ResourceManager.GetString("OfflineStorageFolderSelectionDialogCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OfflineStorageFolderSelectionDialogOK {
            get {
                return ResourceManager.GetString("OfflineStorageFolderSelectionDialogOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        public static string OfflineStorageFolderSelectionDialogTitle {
            get {
                return ResourceManager.GetString("OfflineStorageFolderSelectionDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild was cancelled.
        /// </summary>
        public static string RebuildCancelNotification {
            get {
                return ResourceManager.GetString("RebuildCancelNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild failed.
        /// </summary>
        public static string RebuildErrorNotification {
            get {
                return ResourceManager.GetString("RebuildErrorNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild source, target and target incomplete folders must be distinct..
        /// </summary>
        public static string RebuildFoldersMustBeDistinct {
            get {
                return ResourceManager.GetString("RebuildFoldersMustBeDistinct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string RebuildPageBrowse {
            get {
                return ResourceManager.GetString("RebuildPageBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a database to rebuild files.
        /// </summary>
        public static string RebuildPageNoDatabaseSelectedSubtitle {
            get {
                return ResourceManager.GetString("RebuildPageNoDatabaseSelectedSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No database selected.
        /// </summary>
        public static string RebuildPageNoDatabaseSelectedTitle {
            get {
                return ResourceManager.GetString("RebuildPageNoDatabaseSelectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove source.
        /// </summary>
        public static string RebuildPageRemoveSource {
            get {
                return ResourceManager.GetString("RebuildPageRemoveSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source folder.
        /// </summary>
        public static string RebuildPageSourceFolder {
            get {
                return ResourceManager.GetString("RebuildPageSourceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string RebuildPageStart {
            get {
                return ResourceManager.GetString("RebuildPageStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target folder.
        /// </summary>
        public static string RebuildPageTargetFolder {
            get {
                return ResourceManager.GetString("RebuildPageTargetFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building {0} ....
        /// </summary>
        public static string RebuildProgressBuildingFormat {
            get {
                return ResourceManager.GetString("RebuildProgressBuildingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled..
        /// </summary>
        public static string RebuildProgressCanceled {
            get {
                return ResourceManager.GetString("RebuildProgressCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed at {0}..
        /// </summary>
        public static string RebuildProgressCompletedFormat {
            get {
                return ResourceManager.GetString("RebuildProgressCompletedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string RebuildProgressErrorFormat {
            get {
                return ResourceManager.GetString("RebuildProgressErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hashing {0} ....
        /// </summary>
        public static string RebuildProgressHashingFormat {
            get {
                return ResourceManager.GetString("RebuildProgressHashingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending....
        /// </summary>
        public static string RebuildProgressPending {
            get {
                return ResourceManager.GetString("RebuildProgressPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning....
        /// </summary>
        public static string RebuildProgressScanning {
            get {
                return ResourceManager.GetString("RebuildProgressScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started....
        /// </summary>
        public static string RebuildProgressStarted {
            get {
                return ResourceManager.GetString("RebuildProgressStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matched.
        /// </summary>
        public static string RebuildResultMatchedNoCountLabel {
            get {
                return ResourceManager.GetString("RebuildResultMatchedNoCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matched ({0}).
        /// </summary>
        public static string RebuildResultMatchedWithCountLabel {
            get {
                return ResourceManager.GetString("RebuildResultMatchedWithCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused.
        /// </summary>
        public static string RebuildResultUnusedNoCountLabel {
            get {
                return ResourceManager.GetString("RebuildResultUnusedNoCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused ({0}).
        /// </summary>
        public static string RebuildResultUnusedWithCountLabel {
            get {
                return ResourceManager.GetString("RebuildResultUnusedWithCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild source folder is not configured..
        /// </summary>
        public static string RebuildSourceFolderNotConfigured {
            get {
                return ResourceManager.GetString("RebuildSourceFolderNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild source folder does not exist..
        /// </summary>
        public static string RebuildSourceFolderNotExist {
            get {
                return ResourceManager.GetString("RebuildSourceFolderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild completed.
        /// </summary>
        public static string RebuildSuccessNotification {
            get {
                return ResourceManager.GetString("RebuildSuccessNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild target folder does not exist..
        /// </summary>
        public static string RebuildTargetFolderNotConfigured {
            get {
                return ResourceManager.GetString("RebuildTargetFolderNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials.
        /// </summary>
        public static string RedumpCredentialsStatusError {
            get {
                return ResourceManager.GetString("RedumpCredentialsStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing credentials....
        /// </summary>
        public static string RedumpCredentialsStatusInProgress {
            get {
                return ResourceManager.GetString("RedumpCredentialsStatusInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successful.
        /// </summary>
        public static string RedumpCredentialsStatusSuccess {
            get {
                return ResourceManager.GetString("RedumpCredentialsStatusSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download canceled.
        /// </summary>
        public static string RedumpDownloadStatusCanceled {
            get {
                return ResourceManager.GetString("RedumpDownloadStatusCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download completed at {0}.
        /// </summary>
        public static string RedumpDownloadStatusCompleteFormat {
            get {
                return ResourceManager.GetString("RedumpDownloadStatusCompleteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download error: {0}.
        /// </summary>
        public static string RedumpDownloadStatusErrorFormat {
            get {
                return ResourceManager.GetString("RedumpDownloadStatusErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading ({0} of {1}): {2} for {3}.
        /// </summary>
        public static string RedumpDownloadStatusInProgressFormat {
            get {
                return ResourceManager.GetString("RedumpDownloadStatusInProgressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download started.
        /// </summary>
        public static string RedumpDownloadStatusStarted {
            get {
                return ResourceManager.GetString("RedumpDownloadStatusStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan was cancelled.
        /// </summary>
        public static string ScanCancelNotification {
            get {
                return ResourceManager.GetString("ScanCancelNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan failed.
        /// </summary>
        public static string ScanErrorNotification {
            get {
                return ResourceManager.GetString("ScanErrorNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning {0} ....
        /// </summary>
        public static string ScanFolderProgressScanningFormat {
            get {
                return ResourceManager.GetString("ScanFolderProgressScanningFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled..
        /// </summary>
        public static string ScanProgressCanceled {
            get {
                return ResourceManager.GetString("ScanProgressCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed at {0}..
        /// </summary>
        public static string ScanProgressCompletedFormat {
            get {
                return ResourceManager.GetString("ScanProgressCompletedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string ScanProgressErrorFormat {
            get {
                return ResourceManager.GetString("ScanProgressErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hashing {0} ....
        /// </summary>
        public static string ScanProgressHashingFormat {
            get {
                return ResourceManager.GetString("ScanProgressHashingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending..
        /// </summary>
        public static string ScanProgressPending {
            get {
                return ResourceManager.GetString("ScanProgressPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning....
        /// </summary>
        public static string ScanProgressScanning {
            get {
                return ResourceManager.GetString("ScanProgressScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started..
        /// </summary>
        public static string ScanProgressStarted {
            get {
                return ResourceManager.GetString("ScanProgressStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matched.
        /// </summary>
        public static string ScanResultMatchedNoCountLabel {
            get {
                return ResourceManager.GetString("ScanResultMatchedNoCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matched ({0}).
        /// </summary>
        public static string ScanResultMatchedWithCountLabel {
            get {
                return ResourceManager.GetString("ScanResultMatchedWithCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing.
        /// </summary>
        public static string ScanResultMissingNoCountLabel {
            get {
                return ResourceManager.GetString("ScanResultMissingNoCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing ({0}).
        /// </summary>
        public static string ScanResultMissingWithCountLabel {
            get {
                return ResourceManager.GetString("ScanResultMissingWithCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused.
        /// </summary>
        public static string ScanResultUnusedNoCountLabel {
            get {
                return ResourceManager.GetString("ScanResultUnusedNoCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused ({0}).
        /// </summary>
        public static string ScanResultUnusedWithCountLabel {
            get {
                return ResourceManager.GetString("ScanResultUnusedWithCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Name.
        /// </summary>
        public static string ScanResultWrongNameNoCountLabel {
            get {
                return ResourceManager.GetString("ScanResultWrongNameNoCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Name ({0}).
        /// </summary>
        public static string ScanResultWrongNameWithCountLabel {
            get {
                return ResourceManager.GetString("ScanResultWrongNameWithCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string ScanStatusFilterAll {
            get {
                return ResourceManager.GetString("ScanStatusFilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string ScanStatusFilterComplete {
            get {
                return ResourceManager.GetString("ScanStatusFilterComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing.
        /// </summary>
        public static string ScanStatusFilterMissing {
            get {
                return ResourceManager.GetString("ScanStatusFilterMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial.
        /// </summary>
        public static string ScanStatusFilterPartial {
            get {
                return ResourceManager.GetString("ScanStatusFilterPartial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string ScanStatusFilterUnknown {
            get {
                return ResourceManager.GetString("ScanStatusFilterUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Name.
        /// </summary>
        public static string ScanStatusFilterWrongName {
            get {
                return ResourceManager.GetString("ScanStatusFilterWrongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan completed.
        /// </summary>
        public static string ScanSuccessNotification {
            get {
                return ResourceManager.GetString("ScanSuccessNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2022 Hugues Valois. All rights reserved..
        /// </summary>
        public static string SettingsPageAboutCopyright {
            get {
                return ResourceManager.GetString("SettingsPageAboutCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project on GitHub.
        /// </summary>
        public static string SettingsPageAboutGitHubTitle {
            get {
                return ResourceManager.GetString("SettingsPageAboutGitHubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/huguesv/checksumtools.
        /// </summary>
        public static string SettingsPageAboutGitHubUrl {
            get {
                return ResourceManager.GetString("SettingsPageAboutGitHubUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this app.
        /// </summary>
        public static string SettingsPageAboutGroup {
            get {
                return ResourceManager.GetString("SettingsPageAboutGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checksum Database Manager.
        /// </summary>
        public static string SettingsPageAboutTitle {
            get {
                return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 2.0.
        /// </summary>
        public static string SettingsPageAboutVersion {
            get {
                return ResourceManager.GetString("SettingsPageAboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add folder.
        /// </summary>
        public static string SettingsPageDatabaseFoldersAdd {
            get {
                return ResourceManager.GetString("SettingsPageDatabaseFoldersAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string SettingsPageDatabaseFoldersRemove {
            get {
                return ResourceManager.GetString("SettingsPageDatabaseFoldersRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the folders that contain database files.
        /// </summary>
        public static string SettingsPageDatabaseFoldersSubtitle {
            get {
                return ResourceManager.GetString("SettingsPageDatabaseFoldersSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database folders.
        /// </summary>
        public static string SettingsPageDatabaseFoldersTitle {
            get {
                return ResourceManager.GetString("SettingsPageDatabaseFoldersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to permanently delete the contents of &apos;{0}&apos;?
        ///
        ///All files and subfolders will be lost..
        /// </summary>
        public static string SettingsPageDeleteRedumpFolderContentsMessageFormat {
            get {
                return ResourceManager.GetString("SettingsPageDeleteRedumpFolderContentsMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract files from archives to calculate checksums instead of using the crc32 stored in the archive.
        /// </summary>
        public static string SettingsPageExtractFilesForChecksumSubtitle {
            get {
                return ResourceManager.GetString("SettingsPageExtractFilesForChecksumSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract files to calculate checksums.
        /// </summary>
        public static string SettingsPageExtractFilesForChecksumTitle {
            get {
                return ResourceManager.GetString("SettingsPageExtractFilesForChecksumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit.
        /// </summary>
        public static string SettingsPageGroupAudit {
            get {
                return ResourceManager.GetString("SettingsPageGroupAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string SettingsPageGroupColors {
            get {
                return ResourceManager.GetString("SettingsPageGroupColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string SettingsPageGroupLibrary {
            get {
                return ResourceManager.GetString("SettingsPageGroupLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which app theme to display.
        /// </summary>
        public static string SettingsPageThemeSubtitle {
            get {
                return ResourceManager.GetString("SettingsPageThemeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App theme.
        /// </summary>
        public static string SettingsPageThemeTitle {
            get {
                return ResourceManager.GetString("SettingsPageThemeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string SettingsPageVersionFormat {
            get {
                return ResourceManager.GetString("SettingsPageVersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container count.
        /// </summary>
        public static string StatisticContainerCount {
            get {
                return ResourceManager.GetString("StatisticContainerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database count.
        /// </summary>
        public static string StatisticDatabaseCount {
            get {
                return ResourceManager.GetString("StatisticDatabaseCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total file count.
        /// </summary>
        public static string StatisticFileCount {
            get {
                return ResourceManager.GetString("StatisticFileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total size.
        /// </summary>
        public static string StatisticFileSizeTotal {
            get {
                return ResourceManager.GetString("StatisticFileSizeTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use system setting.
        /// </summary>
        public static string ThemeWindowsDefault {
            get {
                return ResourceManager.GetString("ThemeWindowsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string ToggleSwitchOff {
            get {
                return ResourceManager.GetString("ToggleSwitchOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string ToggleSwitchOn {
            get {
                return ResourceManager.GetString("ToggleSwitchOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string ValidateFileActualNotApplicable {
            get {
                return ResourceManager.GetString("ValidateFileActualNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file extension &apos;{0}&apos; is not supported..
        /// </summary>
        public static string ValidateFileFormatNotSupported {
            get {
                return ResourceManager.GetString("ValidateFileFormatNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        public static string ValidateFileStatusFail {
            get {
                return ResourceManager.GetString("ValidateFileStatusFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miss.
        /// </summary>
        public static string ValidateFileStatusMiss {
            get {
                return ResourceManager.GetString("ValidateFileStatusMiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        public static string ValidateFileStatusPass {
            get {
                return ResourceManager.GetString("ValidateFileStatusPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string ValidatePageBrowse {
            get {
                return ResourceManager.GetString("ValidatePageBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a .sfv or .md5 file to validate its contents.
        /// </summary>
        public static string ValidatePageSubtitle {
            get {
                return ResourceManager.GetString("ValidatePageSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate using a checksum file.
        /// </summary>
        public static string ValidatePageTitle {
            get {
                return ResourceManager.GetString("ValidatePageTitle", resourceCulture);
            }
        }
    }
}
